language: ruby
sudo: false
cache: bundler
rvm:
  - 2.0.0
  - 2.1.0
  - 2.1.1
matrix:
  allow_failures:
    - rvm: 2.1.1
notifications:
  email: false
install:
  - bundle install
  - npm install bower
  - npm install
  - bundle exec bower update
