#!/bin/bash -l

set -e

if [ -f /.dockerenv ]; then
    source ~/.bashrc
    rvm use default
    bundle config github.com $GITHUB_USER:$GITHUB_PASS
fi

export RAILS_ENV=test
export BUNDLE_WITHOUT=development:build
export PATH=./node_modules/.bin:$PATH

exit_code=0

function run {
    declare -a tests_command=("$@")

    echo ''
    echo "=== Running \`${tests_command[*]}\`"
    if ! ${tests_command[*]}; then
        echo "=== These tests failed."
        exit_code=1
    fi
}

function info {
    declare -a info_command=("$@")
    echo ''
    echo "=== Running for informational purposes \`${info_command[*]}\`"
    if ! ${info_command[*]}; then
        echo "== This test has errors and/or warnings. Please review results"
    fi
}

run npm install
run bundle install --quiet
run bundle update brakeman --quiet
run bower install --allow-root
run bundle exec rspec
run sass assets/stylesheets/_templates/karma_tests.scss spec/js/fixtures/stylesheets/lib.css
run npm test
run jscs assets/js
info brakeman -q --no-pager --ensure-latest

if [ -f /.dockerenv ]; then
  run bundle exec danger --dangerfile=jenkins/Dangerfile --verbose
fi

exit "$exit_code"
