#!/bin/bash -l

set -e

if [ -f /.dockerenv ]; then
    source ~/.bashrc
    rvm use default
fi

export RAILS_ENV=production

exit_code=0

function run {
    declare -a build_command=("$@")
    echo ''
    echo "=== Running \`${build_command[*]}\`"
    if ! ${build_command[*]}; then
        echo "=== This build failed."
        exit_code=1
    fi
}

# (re)install node packages to local dir before tests run

run npm install
run bundle install
run gem build dough-ruby.gemspec
run gem inabox *.gem -g http://gems.dev.mas.local

exit "$exit_code"
