#!/bin/bash

set -e

export RAILS_ENV=test
export BUNDLE_WITHOUT=development:build
export PATH=./node_modules/.bin:$PATH

exit_code=0

function run {
    declare -a tests_command=("$@")

    echo ''
    echo "=== Running \`${tests_command[*]}\`"
    if ! ${tests_command[*]}; then
        echo "=== These tests failed."
        exit_code=1
    fi
}

# (re)install node packages to local dir before tests run
run npm install
run bundle install
run bower install --allow-root
run brakeman -q --no-pager --ensure-latest
run bundle exec rspec
run sass assets/stylesheets/_templates/karma_tests.scss spec/js/fixtures/stylesheets/lib.css
run npm test
run jscs assets/js

exit "$exit_code"
