name: Test

on: push

jobs:
  test:
    name: Run tests

    runs-on: ubuntu-latest
    env:
      RAILS_ENV: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler: 1.17.2
          bundler-cache: true

      - name: Setup Node.js environment
        uses: actions/setup-node@v3.5.1
        with:
          node-version: '14.x'

      - name: Install JS packages
        run: npm install && npm install -g bower && bower install

      - name: Add node modules to PATH
        run: echo "./node_modules/.bin" >> $GITHUB_PATH

      - name: Lint Ruby
        run: bundle exec rubocop

      - name: Lint JS
        run: jscs assets/js

      - name: Run tests
        run: bundle exec rspec && karma start spec/js/karma.conf.js --single-run
